### ISSUE TITLE
Cross-Identity Reenactment results not so good?

### ISSUE THREAD

**Issue by c1a1o1** [FeiiYin/StyleHEAT#12]
Cross-Identity Reenactment results not so good?
![40](https://user-images.githubusercontent.com/7991905/180114178-52eec354-7707-40e7-831c-c5bcf084c297.jpg)

https://user-images.githubusercontent.com/7991905/180114285-89b550da-150a-4a07-a9fd-29715211ba8e.mp4

**Comment by FeiiYin** [comment]
I cannot load the videos correctly to see the results.
But indeed, the GAN inversion method is not perfect and the warping procedure will raise artifacts in the cross-id scenarios.
The artifacts may be solved in the future.

**Comment by Shotsordsoo** [comment]
Can't load videos on post either, tried download image and run cross-id reenactment on my own system, worked nicely for me.
https://user-images.githubusercontent.com/16696685/206864685-bebda9f8-53c4-49dd-997c-577467779ef9.mp4

**Comment by FeiiYin** [comment]
Ok, now I can watch the videos. I recommend using the optimization-based inversion methods, e.g. PTI or BaberShop to inverse the target identity. The identity will be strongly improved compared with the encoder-based inversion methods.
The cross-id scenario will distort the original face, which is due to the incomplete decoupled identity information introduced by 3dmm. Incorporating information-bottleneck blocks to filter the information may help.
