### ISSUE TITLE
Cross-Identity Reenactment

### ISSUE THREAD

**Issue by cmmclee** [FeiiYin/StyleHEAT#8]
The identity of the generated video is different from that of the input image.
Is this an inherent problem？How to fix it?
Thanks

**Comment by cmmclee** [comment]
#12

**Comment by FeiiYin** [comment]
Thanks for your attention.
I recommend using the optimization-based inversion methods, e.g. PTI or BaberShop to inverse the target identity. The identity will be strongly improved compared with the encoder-based inversion methods.
The cross-id scenario will distort the original face, which is due to the incomplete decoupled identity information introduced by 3dmm. Incorporating information-bottleneck blocks to filter the information may help.
